---
- hosts: all
  #remote_user: cpadmin
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: copy Docker Compose files
    copy:
      src: ../files/graylog/{{ item }}
      dest: /home/cpadmin/graylog/{{ item }}
    loop:
    - docker-compose.yml
  # Install prerequisites
#  - name: prerequisites
# Need to figure out how to do the following:
# sudo timedatectl set-timezone UTC
# echo -n YourPassword_with16Char | shasum -a 256
## Increase the Physical Volume (pv) to max size
# pvresize /dev/sda3

# Expand the Logical Volume (LV) to max size to match
# lvresize -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv

# Expand the filesystem itself
# resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
# edit /etc/fstab
# /dev/disk/by-uuid/db8ffb61-7be8-4a41-8ae8-522e16e21045  /mnt/sdb        ext4    defaults        0       1
# create docker volume
# sudo docker volume create --driver=local --label=log_data --opt type=none --opt device=/mnt/sdb/data/_data  graylog_log_data
# stop docker, then move graylog_log_data volume to .bak
# create a link to the new mounted volume
#  sudo ln /mnt/sdb/data/ /var/lib/docker/volumes/graylog_log_data

  # use files parameter to use multiple docker-compose.yml files
  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /home/cpadmin/graylog
      files:
      - docker-compose.yml
      
#  - name: Run container
#    become: True
#    shell:
#      cmd: "docker-compose -f docker-compose.yml up -d"
#      chdir: /home/cpadmin/graylog
